### ISSUE TITLE
Exception when full-width space is described

### ISSUE THREAD

**Issue by KT1061** [krisds/koopa#30] opened 2023-03-07 03:10 UTC
Hello.

I'm using COBOL koopa parser and I'm getting some exception during parsing.
If there is a line in the COBOL source code that contains full-width space up to column 7 and ends within column 7, an exception will occur and the analysis will stop halfway.

I tried to investigate this exception, but I couldn't identify the cause and it was difficult to fix, so does anyone know the cause?

I will send you the source code where this exception occurs.

```
       IDENTIFICATION                   DIVISION.
       PROGRAM-ID.                      SAMPLE-01.
      *
       ENVIRONMENT                      DIVISION.
      *
       DATA                             DIVISION.
      *
       PROCEDURE                        DIVISION.
       MAIN.
           DISPLAY "Hello world!"  UPON CONSOLE.
　    *
           STOP RUN.

```

**Comment by krisds** [comment] 2023-03-07 06:34
I'll take a look!

**Comment by krisds** [comment] 2023-03-07 06:46
It works for me without exception with the latest version in master, as you can see from this screenshot:

<img width="1003" alt="Screenshot 2023-03-07 at 07 39 24" src="https://user-images.githubusercontent.com/4458144/223343395-9e787c57-3299-4aa0-ad72-1492e8d7f0d4.png">

The full-width space is there (the 3000 in the hex panel). 

Could you perhaps share the stacktrace of the exception on your side ?

**Comment by KT1061** [comment] 2023-03-30 08:34
Sorry for my late reply.
I tried to analyze the source code with double-byte spaces, but it seems that the analysis has failed as shown in the image below.
![image2023-3-28_14-7-49](https://user-images.githubusercontent.com/127075113/228777385-3f8b600b-a709-4f00-95b0-9f13ef1b72f0.png)

In patterns that do not contain double-byte spaces, "PROGRAM" is judged to be commented out (which is the expected behavior).
![image2023-3-28_13-59-16](https://user-images.githubusercontent.com/127075113/228777650-e65ed1c0-020c-4a5d-9c1f-692517f915a2.png)

In patterns containing double-byte spaces, "PROGRAM" is converted to "@PROGRAM_TEXT_AREA" and "@WORD", and that it is not processed as a comment out (which is NOT the expected behavior).
![image2023-3-28_13-48-7](https://user-images.githubusercontent.com/127075113/228778076-ba8d44c6-7e04-46ee-b024-62e54674d382.png)

Do community results differ from this result?

**Comment by krisds** [comment] 2023-03-30 19:51
Very odd. I'm wondering if it might be due to a difference in runtime environment. What version of Java are you using to build and run ?

**Comment by KT1061** [comment] 2023-04-03 07:06
I use the following versions in my environment.

openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

**Comment by krisds** [comment] 2023-04-10 06:07
So I just tried with:
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
And it parsed the file here without any problem.

So what could you do next ?

The easy workaround would probably be to preprocess your source files and replace all full-width spaces with regular ones before passing them into Koopa. That's not very satisfactory, but should at least get you unblocked.

To get a real fix you'll have to do some debugging yourself. Maybe try a more recent version of Java ? Or try running it on another PC ? Or dive into the code and active the debugger. I think `ProgramArea.tokenizeLine` should make a good starting poing for that.

Sorry I can't be of more direct help with this issue.

**Comment by KT1061** [comment] 2023-04-13 04:34
I tried updating to the latest version, but it didn't fix the problem.
However, when I changed to the latest version, I needed to change the file encoding.
This is probably because the file encoding was changed from MS932 to UTF-8 because it was running in the Windows10 environment.
Just in case, I will give you the UTF-8 source used for verification, so could you check it again using this?

As for the exception, it was caused by something we made on our side, so it was not a problem with krisds's code.
However, when I parse the COBOL file I gave you with the code that does not include the correction, it seems that the analysis is not completed to the end.
krisds, can you kindly check if you can reproduce this at your side?

In FullWithSpace.cbl, it seems that the problem is triggered by misjudgment of commented out lines with double-byte spaces. 
MultiByte.cbl seems to trigger the problem because it contains full-width characters that are not full-width spaces.

[KT1061.zip](https://github.com/krisds/koopa/files/11218168/KT1061.zip)

**Comment by krisds** [comment] 2023-04-13 05:14
Yes, I can reproduce the problem you are seeing on my own machine now!

I will try to take a look soon at what might be causing the problem.

**Comment by krisds** [comment] 2023-04-13 16:58
I have fixed it, and pushed the fix to master.

Here are some screenshots showing the fix working on my machine:


<img width="1452" alt="Screenshot 2023-04-13 at 18 48 03" src="https://user-images.githubusercontent.com/4458144/231831426-ab20cf66-2019-4b70-9651-d228fa46abae.png">



<img width="1452" alt="Screenshot 2023-04-13 at 18 48 13" src="https://user-images.githubusercontent.com/4458144/231831222-cb668eef-d596-4056-b765-302406582223.png">



Can you try it out on your system, and let me know if it looks good on your side as well ?

**Comment by KT1061** [comment] 2023-04-25 10:38
thank you.
We have confirmed that full-width spaces are also supported in this environment, but some full-width characters other than full-width spaces are not supported.
Specifically, if double-byte characters are contained within 72 columns, the program identification area after the 73rd column cannot be determined.
I suspect that this is probably due to the fact that full-width characters other than full-width spaces are not processed as two columns.
I will send you the new source code, so could you please modify it so that it can handle double-byte characters in the following source code?

It seems that the data names on the 12th and 13th lines are also handled incorrectly.
Could you please confirm this as well?

[KT1061.zip](https://github.com/krisds/koopa/files/11321603/KT1061.zip)

**Comment by krisds** [comment] 2023-04-30 07:10
I see a lot of these  "Replacement characters" (FFFD) which a quick Google tells me are "used to replace an unknown, unrecognized, or unrepresentable character". I'm assuming, though, that these are real characters in the original source code. Did something go wrong with the conversion ? Am I using a bad encoding ? I'm sorry, but I'm not sure if this is a problem with the input, or with the code.

<img width="1452" alt="Screenshot 2023-04-30 at 09 06 38" src="https://user-images.githubusercontent.com/4458144/235340490-07d84d77-6dd1-454d-a399-00affbaf2f85.png">

**Comment by krisds** [comment] 2023-04-30 10:24
I figured out I had to set the endocing to "Shift_JIS" (`-Dkoopa.encoding=Shift_JIS`). Now I still have to work out why the size is calculated in the wrong way...

<img width="1452" alt="Screenshot 2023-04-30 at 12 22 33" src="https://user-images.githubusercontent.com/4458144/235348029-6347c36a-e717-47f7-b7e3-cb8bdc6b363e.png">

**Comment by krisds** [comment] 2023-04-30 11:10
This looks better now. The update is in master for your testing.

![Screenshot 2023-04-30 at 12 54 06](https://user-images.githubusercontent.com/4458144/235349778-19fb4000-fd9d-4557-985e-f05406d75449.png)

**Comment by KT1061** [comment] 2023-05-29 01:51
My sincere apologies that I could not reply for a long time.
I can confirm that (thanks to your efforts) it is now possible to support double-byte characters that could not be supported before, and the problem has been solved.

It was a long exchange, but thank you for your patience in responding to multiple problems, which was not limited to just this single issue.
I will continue using koopa COBOL parser in the future too.

**Comment by krisds** [comment] 2023-05-29 06:00
No worries. Glad to hear we got it solved!

**Closed by krisds** 2023-05-29 06:00 UTC
